using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CoreReactApp.Server.Migrations
{
    /// <inheritdoc />
    public partial class SeedAirportsData : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
                table: "Airports",
                columns: new[] { "AirportId", "IATACode", "Name", "Location" },
                values: new object[,]
                {
                    { 61, "ATL", "Hartsfield-Jackson Atlanta International Airport", "Atlanta, USA" },
                    { 62, "PEK", "Beijing Capital International Airport", "Beijing, China" },
                    { 63, "LAX", "Los Angeles International Airport", "Los Angeles, USA" },
                    { 64, "DXB", "Dubai International Airport", "Dubai, UAE" },
                    { 65, "HND", "Tokyo Haneda Airport", "Tokyo, Japan" },
                    { 66, "ORD", "O'Hare International Airport", "Chicago, USA" },
                    { 67, "LHR", "London Heathrow Airport", "London, UK" },
                    { 68, "CDG", "Charles de Gaulle Airport", "Paris, France" },
                    { 69, "DFW", "Dallas/Fort Worth International Airport", "Dallas, USA" },
                    { 70, "DEN", "Denver International Airport", "Denver, USA" },
                    { 71, "SIN", "Singapore Changi Airport", "Singapore, Singapore" },
                    { 72, "AMS", "Amsterdam Schiphol Airport", "Amsterdam, Netherlands" },
                    { 73, "ICN", "Incheon International Airport", "Seoul, South Korea" },
                    { 74, "BKK", "Suvarnabhumi Airport", "Bangkok, Thailand" },
                    { 75, "HKG", "Hong Kong International Airport", "Hong Kong, China" },
                    { 76, "JFK", "John F. Kennedy International Airport", "New York, USA" },
                    { 77, "KUL", "Kuala Lumpur International Airport", "Kuala Lumpur, Malaysia" },
                    { 78, "FRA", "Frankfurt Airport", "Frankfurt, Germany" },
                    { 79, "IST", "Istanbul Airport", "Istanbul, Turkey" },
                    { 80, "GRU", "São Paulo/Guarulhos–Governador André Franco Montoro International Airport", "São Paulo, Brazil" },
                    { 81, "MIA", "Miami International Airport", "Miami, USA" },
                    { 82, "SYD", "Sydney Kingsford-Smith Airport", "Sydney, Australia" },
                    { 83, "YVR", "Vancouver International Airport", "Vancouver, Canada" },
                    { 84, "YYZ", "Toronto Pearson International Airport", "Toronto, Canada" },
                    { 85, "MUC", "Munich Airport", "Munich, Germany" },
                    { 86, "SFO", "San Francisco International Airport", "San Francisco, USA" },
                    { 87, "SEA", "Seattle-Tacoma International Airport", "Seattle, USA" },
                    { 88, "LAS", "McCarran International Airport", "Las Vegas, USA" },
                    { 89, "PHX", "Phoenix Sky Harbor International Airport", "Phoenix, USA" },
                    { 90, "MCO", "Orlando International Airport", "Orlando, USA" },
                    { 91, "IAH", "George Bush Intercontinental Airport", "Houston, USA" },
                    { 92, "BOS", "Logan International Airport", "Boston, USA" },
                    { 93, "MAD", "Adolfo Suárez Madrid–Barajas Airport", "Madrid, Spain" },
                    { 94, "BCN", "Barcelona–El Prat Airport", "Barcelona, Spain" },
                    { 95, "GIG", "Rio de Janeiro–Galeão International Airport", "Rio de Janeiro, Brazil" },
                    { 96, "DEL", "Indira Gandhi International Airport", "Delhi, India" },
                    { 97, "BOM", "Chhatrapati Shivaji Maharaj International Airport", "Mumbai, India" },
                    { 98, "JNB", "O. R. Tambo International Airport", "Johannesburg, South Africa" },
                    { 99, "CPT", "Cape Town International Airport", "Cape Town, South Africa" },
                    { 100,"CAI", "Cairo International Airport", "Cairo, Egypt" },
                    { 101,"DOH", "Hamad International Airport", "Doha, Qatar" },
                    { 102,"MEX", "Mexico City International Airport", "Mexico City, Mexico" },
                    { 103,"EZE", "Ministro Pistarini International Airport", "Buenos Aires, Argentina" },
                    { 104,"ZRH", "Zurich Airport", "Zurich, Switzerland" },
                    { 105,"DUB", "Dublin Airport", "Dublin, Ireland" },
                    { 106,"BRU", "Brussels Airport", "Brussels, Belgium" },
                    { 107,"ARN", "Stockholm Arlanda Airport", "Stockholm, Sweden" },
                    { 108,"HEL", "Helsinki Airport", "Helsinki, Finland" },
                    { 109,"OSL", "Oslo Gardermoen Airport", "Oslo, Norway" },
                    { 110,"CPH", "Copenhagen Airport", "Copenhagen, Denmark" },
                    { 111,"VIE", "Vienna International Airport", "Vienna, Austria" },
                    { 112,"PRG", "Václav Havel Airport Prague", "Prague, Czech Republic" },
                    { 113,"WAW", "Warsaw Chopin Airport", "Warsaw, Poland" },
                    { 114,"LIS", "Lisbon Humberto Delgado Airport", "Lisbon, Portugal" },
                    { 115,"LED", "Pulkovo Airport", "Saint Petersburg, Russia" },
                    { 116,"DME", "Domodedovo International Airport", "Moscow, Russia" },
                    { 117,"SVO", "Sheremetyevo International Airport", "Moscow, Russia" },
                    { 118,"TPE", "Taiwan Taoyuan International Airport", "Taipei, Taiwan" },
                    { 119,"MNL", "Ninoy Aquino International Airport", "Manila, Philippines" },
                    { 120,"BNE", "Brisbane Airport", "Brisbane, Australia" },
                    { 121,"ADL", "Adelaide Airport", "Adelaide, Australia" },
                    { 122,"AKL", "Auckland Airport", "Auckland, New Zealand" },
                    { 123,"CHC", "Christchurch International Airport", "Christchurch, New Zealand" },
                    { 124,"DPS", "Ngurah Rai International Airport", "Bali, Indonesia" },
                    { 125,"CGK", "Soekarno-Hatta International Airport", "Jakarta, Indonesia" },
                    { 126,"HAN", "Noi Bai International Airport", "Hanoi, Vietnam" },
                    { 127,"SGN", "Tan Son Nhat International Airport", "Ho Chi Minh City, Vietnam" },
                    { 128,"KIX", "Kansai International Airport", "Osaka, Japan" },
                    { 129,"CTS", "New Chitose Airport", "Sapporo, Japan" },
                    { 130,"NRT", "Narita International Airport", "Narita, Japan" },
                    { 131,"GVA", "Geneva Airport", "Geneva, Switzerland" },
                    { 132,"NCE", "Nice Côte d'Azur Airport", "Nice, France" },
                    { 133,"VCE", "Venice Marco Polo Airport", "Venice, Italy" },
                    { 134,"FCO", "Leonardo da Vinci–Fiumicino Airport", "Rome, Italy" },
                    { 135,"MXP", "Milan Malpensa Airport", "Milan, Italy" },
                    { 136,"NAP", "Naples International Airport", "Naples, Italy" },
                    { 137,"ATH", "Athens International Airport", "Athens, Greece" },
                    { 138,"SKG", "Thessaloniki Airport", "Thessaloniki, Greece" },
                    { 139,"BLL", "Billund Airport", "Billund, Denmark" },
                    { 140,"GOT", "Göteborg Landvetter Airport", "Gothenburg, Sweden" },
                    { 142,"BUD", "Budapest Ferenc Liszt International Airport", "Budapest, Hungary" },
                    { 143,"OTP", "Henri Coanda International Airport", "Bucharest, Romania" },
                    { 144,"SOF", "Sofia Airport", "Sofia, Bulgaria" },
                    { 145,"TBS", "Tbilisi International Airport", "Tbilisi, Georgia" },
                    { 146,"EVN", "Zvartnots International Airport", "Yerevan, Armenia" },
                    { 147,"GYD", "Heydar Aliyev International Airport", "Baku, Azerbaijan" },
                    { 148,"ALA", "Almaty International Airport", "Almaty, Kazakhstan" },
                    { 150,"CCU", "Netaji Subhas Chandra Bose International Airport", "Kolkata, India" },
                    { 151,"BLR", "Kempegowda International Airport", "Bangalore, India" },
                    { 152,"HYD", "Rajiv Gandhi International Airport", "Hyderabad, India" },
                    { 153,"MAA", "Chennai International Airport", "Chennai, India" },
                    { 154,"KTM", "Tribhuvan International Airport", "Kathmandu, Nepal" },
                    { 155,"DAC", "Hazrat Shahjalal International Airport", "Dhaka, Bangladesh" },
                    { 156,"CMB", "Bandaranaike International Airport", "Colombo, Sri Lanka" },
                    { 157,"MLE", "Velana International Airport", "Malé, Maldives" },
                    { 158,"JED", "King Abdulaziz International Airport", "Jeddah, Saudi Arabia" },
                    { 159,"RUH", "King Khalid International Airport", "Riyadh, Saudi Arabia" },
                    { 160,"DMM", "King Fahd International Airport", "Dammam, Saudi Arabia" },
                    { 161,"AMM", "Queen Alia International Airport", "Amman, Jordan" },
                    { 162,"TLV", "Ben Gurion Airport", "Tel Aviv, Israel" },
                    { 163,"BEY", "Beirut–Rafic Hariri International Airport", "Beirut, Lebanon" },
                    { 165,"AUH", "Abu Dhabi International Airport", "Abu Dhabi, UAE" },
                    { 166,"SHJ", "Sharjah International Airport", "Sharjah, UAE" },
                    { 167,"KWI", "Kuwait International Airport", "Kuwait City, Kuwait" },
                    { 168,"BAH", "Bahrain International Airport", "Manama, Bahrain" },
                    { 169,"MCT", "Muscat International Airport", "Muscat, Oman" },
                    { 170,"ISB", "Islamabad International Airport", "Islamabad, Pakistan" },
                    { 171,"LHE", "Allama Iqbal International Airport", "Lahore, Pakistan" },
                    { 172,"KHI", "Jinnah International Airport", "Karachi, Pakistan" },
                    { 174,"PNQ", "Pune Airport", "Pune, India" },
                    { 175,"GOI", "Dabolim Airport", "Goa, India" },
                    { 176,"TRV", "Trivandrum International Airport", "Thiruvananthapuram, India" },
                    { 177,"COK", "Cochin International Airport", "Kochi, India" },
                    { 178,"IXC", "Chandigarh International Airport", "Chandigarh, India" },
                    { 179,"GAU", "Lokpriya Gopinath Bordoloi International Airport", "Guwahati, India" },
                    { 180,"IXB", "Bagdogra International Airport", "Siliguri, India" },
                    { 181,"PAT", "Jay Prakash Narayan Airport", "Patna, India" },
                    { 182,"VNS", "Lal Bahadur Shastri Airport", "Varanasi, India" },
                    { 183,"JAI", "Jaipur International Airport", "Jaipur, India" },
                    { 184,"AMD", "Sardar Vallabhbhai Patel International Airport", "Ahmedabad, India" },
                    { 185,"BDQ", "Vadodara Airport", "Vadodara, India" },
                    { 186,"IDR", "Devi Ahilyabai Holkar Airport", "Indore, India" },
                    { 187,"BHO", "Raja Bhoj Airport", "Bhopal, India" },
                    { 188,"NAG", "Dr. Babasaheb Ambedkar International Airport", "Nagpur, India" },
                    { 189,"RPR", "Swami Vivekananda Airport", "Raipur, India" },
                    { 190,"VGA", "Vijayawada Airport", "Vijayawada, India" },
                    { 191,"IXR", "Birsa Munda Airport", "Ranchi, India" },
                    { 192,"IXT", "Imphal Airport", "Imphal, India" },
                    { 193,"JMU", "Jammu Airport", "Jammu, India" },
                    { 194,"SLV", "Salem Airport", "Salem, India" },
                    { 195,"IXD", "Allahabad Airport", "Allahabad, India" },
                    { 196,"SXR", "Sheikh ul-Alam International Airport", "Srinagar, India" },
                    { 197,"IXA", "Agartala Airport", "Agartala, India" },
                    { 198,"BOM", "Chhatrapati Shivaji Maharaj International Airport", "Mumbai, India" },
                    { 199,"DEL", "Indira Gandhi International Airport", "Delhi, India" },
                    { 855,"ZAG", "Zagreb Franjo Tudman Airport", "Zagreb, Croatia" },
                    { 857,"DEL", "Split Airport", "Split, Croatia" }
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            for (int id = 61; id <= 100; id++)
            {
                migrationBuilder.DeleteData(
                    table: "Airports",
                    keyColumn: "AirportId",
                    keyValue: id);
            }
        }
    }
}
